"""empty message

Revision ID: 26d4b99b2ee7
Revises: 5a82a7f5c97a
Create Date: 2022-08-06 08:47:09.077820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26d4b99b2ee7'
down_revision = '5a82a7f5c97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre')
    op.drop_table('artist_genre')
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('artist_genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='artist_genre_artist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='artist_genre_pkey')
    )
    op.create_table('venue_genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='venue_genre_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='venue_genre_pkey')
    )
    # ### end Alembic commands ###
